### PR TITLE
adding the directory option back

### PR DESCRIPTION
**Pull request by albancreton**
- Adds the [directory option](https://github.com/webpack-contrib/s3-plugin-webpack#options) from `s3-plugin-webpack` back.

### CODE REVIEW

**Comment by matrus2** [comment]
Tests not passed. It would be great if you could provide your own test showing the functionality is working as expected.

**Comment by albancreton** [comment]
@matrus2 It would be great if you provide some help to navigate around you tests so I can plug some for that feature. it's pretty simple to test (specially when mocking fs) but I can't have the current tests to pass locally...

**Comment by matrus2** [comment]
@albancreton As you can see from travis output, there is a problem in the code not in the breaking tests. To run integration tests for yourself you should set values of environmental variables listed in `.env.sample` file, to do it you need to configure related AWS services. Locally you can make use of `npm link` mode.

**Comment by albancreton** [comment]
yep, figured it out tracking down the original repository. I can run the whole test suit locally, and everything is passing... I assume it's because of the outdate version of node on the CI.
BTW, looks like your latest master build failed too...

**Comment by matrus2** [comment]
Bumping up to 9.

**Comment by matrus2** [comment]
Any update on this? @albancreton

**Comment by MikaAK** [comment]
@albancreton If you need this feature https://github.com/MikaAK/s3-plugin-webpack is back in my control and being maintained again after being stuck by processes from webpack-contrib, it has the directory option

**Pull request closed without merging**
