### PR TITLE
Webpack 5 Support

### PR DESCRIPTION
**Pull request by samageloff**
Hey @matrus2,

Thanks so much for the plugin! I've been in the process of upgrading Webpack from 4 to 5, to test some new features. This plugin was breaking, and so here's a fix. I wasn't able to run tests, as I don't have the config saved. 

If we can get the tests to pass, would you be up for a v2 release? :)

S

### CODE REVIEW

**Comment by matrus2** [comment]
Hi, 

First of all I would like to thank for the PR. Here is the output of CI flow:

https://travis-ci.org/github/matrus2/webpack-s3-uploader

I think instead of one lint error you need to bump up webpack version to 5 in dev dependencies as it is used in tests.

**Comment by samageloff** [comment]
@matrus2 good catch. I think I had it upgraded locally, but hadn't saved it. It should be up now. Resolved the lint issue as well. It looks like the test error feedback is more clear now. I may be able to figure those out now. Will send another PR when I get a chance.

**Comment by matrus2** [comment]
Still there is something wrong in the test configuration. See here:
https://travis-ci.org/github/matrus2/webpack-s3-uploader
I suppose you should use extract-text-webpack-plugin in different way, as suggested here: 
https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage

**Comment by samageloff** [comment]
Got things further w/ that adjustment. The [callback param](https://github.com/matrus2/webpack-s3-uploader/pull/17/files#diff-0bbea6b037d75e7b837231dd0f962b36R86) is no longer available on the `afterEmit` hook. Will need to look into refactoring a bit to handle errors.

Will push the code w/ the replacement of extract text.

**Pull request closed without merging**
